cleaned up test to work well with buildenv

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -14,7 +14,7 @@ export ZOPEN_BOOTSTRAP='skip'
 export ZOPEN_CONFIGURE='skip'
 export ZOPEN_MAKE='skip'
 export ZOPEN_INSTALL='skip'
-export ZOPEN_CHECK='../tests/strdupxmp.sh'
+export ZOPEN_CHECK='../tests/basic.sh'
 export ZOPEN_CHECK_OPTS=''
 
 zopen_check_results()
@@ -23,8 +23,11 @@ zopen_check_results()
   pfx="$2"
   chk="$1/$2_check.log"
 
-  # Echo the following information to guage build health
-  echo "actualFailures:0"
+  if ! grep 'Test passed' "${chk}" ; then
+    echo "actualFailures:0"
+  else
+    echo "actualFailures:1"
+  fi
   echo "totalTests:1"
   echo "expectedFailures:0"
 }
